/**
 * Calculate HSL Tokens Tool
 * Converts hex colors to Optics HSL format tokens
 * (Renamed from generate_theme for clarity - focused on the calculation aspect)
 */

import { z } from 'zod';
import Tool, { type ToolInputSchema } from '../tool.js';
import { designTokens, type DesignToken } from '../../optics-data.js';
import { generateFigmaVariablesJSON } from '../../utils/figma-tokens.js';
import { readToolFile } from '../../_internal/resource-path.js';

interface BrandColors {
  primary?: string;
  neutral?: string;
  'alerts-warning'?: string;
  'alerts-danger'?: string;
  'alerts-info'?: string;
  'alerts-notice'?: string;
}

interface GeneratedTheme {
  cssVariables: string;
  figmaVariables: string;
  tokens: DesignToken[];
  documentation: string;
}

class CalculateHslTokensTool extends Tool {
  name = 'calculate_hsl_tokens';
  title = 'Calculate HSL Tokens';
  description = 'Convert hex colors to Optics HSL format and generate theme tokens';

  inputSchema = {
    brandName: z
      .string()
      .describe('The name of the brand/theme (e.g., "Acme Corp")'),
    primary: z
      .string()
      .describe('Primary brand color (hex, e.g., "#FF5733")'),
    neutral: z
      .string()
      .optional()
      .describe('Neutral color (hex, optional)')
  };

  async handler(args: ToolInputSchema): Promise<string> {
    const brandColors: BrandColors = {
      primary: args.primary,
      neutral: args.neutral
    };
    const theme = await this.generateTheme(args.brandName, brandColors);

    let output = await readToolFile('generate-theme-output.md');

    output = output
      .replace('{{brandName}}', args.brandName)
      .replace('{{cssVariables}}', theme.cssVariables)
      .replace('{{figmaVariables}}', theme.figmaVariables)
      .replace('{{totalTokens}}', String(theme.tokens.length))
      .replace('{{colorTokens}}', String(theme.tokens.filter(t => t.category === 'color').length))
      .replace('{{typographyTokens}}', String(theme.tokens.filter(t => t.category === 'typography').length))
      .replace('{{spacingTokens}}', String(theme.tokens.filter(t => t.category === 'spacing').length))
      .replace('{{documentation}}', theme.documentation);

    return output;
  }

  /**
   * Generate Optics HSL color tokens from brand colors
   */
  private generateColorTokens(brandColors: BrandColors): DesignToken[] {
    const tokens: DesignToken[] = [];

    const defaults: BrandColors = {
      primary: '#2D6FDB',
      neutral: '#757882',
      'alerts-warning': '#FFD93D',
      'alerts-danger': '#FF6B94',
      'alerts-info': '#2D6FDB',
      'alerts-notice': '#6ACF71'
    };

    const colors = { ...defaults, ...brandColors };

    for (const [family, hex] of Object.entries(colors)) {
      if (!hex) continue;

      const hsl = this.hexToHSL(hex);

      tokens.push({
        name: `op-color-${family}-h`,
        cssVar: `--op-color-${family}-h`,
        value: String(hsl.h),
        category: 'color',
        description: `${family} color hue (HSL) - drives all ${family} scale tokens`
      });

      tokens.push({
        name: `op-color-${family}-s`,
        cssVar: `--op-color-${family}-s`,
        value: `${hsl.s}%`,
        category: 'color',
        description: `${family} color saturation (HSL)`
      });

      tokens.push({
        name: `op-color-${family}-l`,
        cssVar: `--op-color-${family}-l`,
        value: `${hsl.l}%`,
        category: 'color',
        description: `${family} color lightness (HSL)`
      });
    }

    return tokens;
  }

  /**
   * Convert hex to HSL
   */
  private hexToHSL(hex: string): { h: number; s: number; l: number } {
    hex = hex.replace('#', '');

    const r = parseInt(hex.substring(0, 2), 16) / 255;
    const g = parseInt(hex.substring(2, 4), 16) / 255;
    const b = parseInt(hex.substring(4, 6), 16) / 255;

    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    let h = 0;
    let s = 0;
    const l = (max + min) / 2;

    if (max !== min) {
      const d = max - min;
      s = l > 0.5 ? d / (2 - max - min) : d / (max + min);

      switch (max) {
        case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
        case g: h = ((b - r) / d + 2) / 6; break;
        case b: h = ((r - g) / d + 4) / 6; break;
      }
    }

    return {
      h: Math.round(h * 360),
      s: Math.round(s * 100),
      l: Math.round(l * 100)
    };
  }

  /**
   * Generate CSS variables from tokens
   */
  private generateCSSVariables(tokens: DesignToken[], themeName: string = 'default'): string {
    const lines: string[] = [
      `/* ${themeName} Theme - Generated by Optics MCP */`,
      `/* HSL tokens for easy theming */`,
      `:root {`
    ];

    const grouped: Record<string, DesignToken[]> = {};
    tokens.forEach(token => {
      if (!grouped[token.category]) grouped[token.category] = [];
      grouped[token.category].push(token);
    });

    if (grouped['color']) {
      lines.push(`  /* Colors (HSL) */`);
      for (const token of grouped['color']) {
        lines.push(`  --${token.name}: ${token.value};`);
      }
      lines.push('');
    }

    for (const [category, categoryTokens] of Object.entries(grouped)) {
      if (category === 'color') continue;

      lines.push(`  /* ${category.charAt(0).toUpperCase() + category.slice(1)} */`);
      for (const token of categoryTokens) {
        lines.push(`  --${token.name}: ${token.value};`);
      }
      lines.push('');
    }

    lines.push('}');

    return lines.join('\n');
  }

  /**
   * Generate theme documentation
   */
  private async generateDocumentation(themeName: string, tokens: DesignToken[]): Promise<string> {
    let documentation = await readToolFile('generate-theme-instructions.md');

    const stats = tokens.reduce((acc, token) => {
      acc[token.category] = (acc[token.category] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    const tokenSummary = Object.entries(stats)
      .map(([category, count]) => `- **${category}**: ${count} tokens`)
      .join('\n');

    const grouped: Record<string, DesignToken[]> = {};
    tokens.forEach(token => {
      if (!grouped[token.category]) grouped[token.category] = [];
      grouped[token.category].push(token);
    });

    const tokenCategories = Object.entries(grouped)
      .map(([category, categoryTokens]) => {
        const lines = [
          `### ${category.charAt(0).toUpperCase() + category.slice(1)}`,
          '',
          '| Token Name | Value | Description |',
          '|------------|-------|-------------|'
        ];

        for (const token of categoryTokens) {
          lines.push(`| \`${token.name}\` | \`${token.value}\` | ${token.description || ''} |`);
        }

        return lines.join('\n');
      })
      .join('\n\n');

    documentation = documentation
      .replace('{{themeName}}', themeName)
      .replace('{{tokenSummary}}', tokenSummary)
      .replace('{{tokenCategories}}', tokenCategories);

    return documentation;
  }

  /**
   * Main theme generation function
   */
  private async generateTheme(brandName: string, brandColors: BrandColors): Promise<GeneratedTheme> {
    let tokens: DesignToken[] = [...designTokens];

    if (Object.keys(brandColors).length > 0) {
      const customColorTokens = this.generateColorTokens(brandColors);

      tokens = tokens.map(token => {
        const customToken = customColorTokens.find(ct => ct.name === token.name);
        return customToken || token;
      });
    }

    const cssVariables = this.generateCSSVariables(tokens, brandName);
    const figmaVariables = generateFigmaVariablesJSON(tokens, { collectionName: `${brandName} Design System` });
    const documentation = await this.generateDocumentation(brandName, tokens);

    return {
      cssVariables,
      figmaVariables,
      tokens,
      documentation
    };
  }
}

export default CalculateHslTokensTool;
